#!/usr/bin/env bash
# Regenerates .claude/agents/*.md from the vendor-neutral agents/*.md role contracts.
# Usage:
#   scripts/generate-agent-views.sh          # write .claude/agents/*.md
#   scripts/generate-agent-views.sh --check  # verify .claude/agents/*.md is up to date; no writes
set -euo pipefail

# `browser` has no separate `web` member in the fixed capability list, so it covers both
# reaching the public web (WebSearch/WebFetch) and driving a real browser (the chrome MCP tools).
readonly CHROME_MCP_TOOLS="mcp__claude-in-chrome__tabs_context_mcp,mcp__claude-in-chrome__tabs_create_mcp,mcp__claude-in-chrome__tabs_close_mcp,mcp__claude-in-chrome__navigate,mcp__claude-in-chrome__computer,mcp__claude-in-chrome__read_page,mcp__claude-in-chrome__find,mcp__claude-in-chrome__get_page_text,mcp__claude-in-chrome__form_input,mcp__claude-in-chrome__javascript_tool,mcp__claude-in-chrome__read_console_messages,mcp__claude-in-chrome__read_network_requests"
# Every starter agent runs on the same plan tier; model choice is a vendor/plan concern, not
# part of the neutral role contract, so it lives here as a single constant.
readonly AGENT_MODEL="sonnet"

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
agents_dir="$repo_root/agents"
out_dir="$repo_root/.claude/agents"

check_mode=false
case "${1:-}" in
  "") ;;
  --check) check_mode=true ;;
  *)
    echo "usage: $(basename "$0") [--check]" >&2
    exit 2
    ;;
esac
if [[ $# -gt 1 ]]; then
  echo "usage: $(basename "$0") [--check]" >&2
  exit 2
fi

fail() {
  echo "generate-agent-views: $1" >&2
  exit 1
}

# Emits the Claude Code `tools:` value for a normalized, comma-separated capability list.
# `azure`/`github` are policy capabilities reached through `shell` (az/terraform/gh) and add no
# tool of their own.
tools_for_capabilities() {
  local caps=",$1,"
  local -a out=()
  [[ "$caps" == *",files,"* ]] && out+=(Read Edit Write Glob Grep)
  [[ "$caps" == *",shell,"* ]] && out+=(Bash)
  if [[ "$caps" == *",browser,"* ]]; then
    out+=(WebSearch WebFetch)
    IFS=',' read -r -a chrome_tools <<<"$CHROME_MCP_TOOLS"
    out+=("${chrome_tools[@]}")
  fi
  local joined="" t
  # bash 3.2 (macOS's shipped bash) throws "unbound variable" under `set -u` when expanding
  # an empty array directly; the `+"${out[@]}"` idiom substitutes nothing instead of erroring.
  for t in "${out[@]+"${out[@]}"}"; do
    joined+="${joined:+, }$t"
  done
  echo "$joined"
}

# Reads and validates one agents/<role>.md, then writes the generated Claude Code view to stdout.
generate_one() {
  local src="$1" base name description caps_raw caps_norm tools i
  base="$(basename "$src" .md)"

  # Portable read loop (not `mapfile`, which is bash-4-only and macOS ships bash 3.2) that still
  # captures a final line with no trailing newline.
  local -a lines=()
  local line
  while IFS= read -r line || [[ -n "$line" ]]; do
    lines+=("$line")
  done <"$src"

  [[ "${lines[0]:-}" == "---" ]] || fail "$src:1: front matter must open with '---'"
  [[ "${lines[1]:-}" =~ ^name:\ (.+)$ ]] || fail "$src:2: expected 'name: <value>'"
  name="${BASH_REMATCH[1]}"
  [[ "${lines[2]:-}" =~ ^description:\ \"(.*)\"$ ]] || fail "$src:3: expected a single-line double-quoted 'description: \"...\"'"
  description="${BASH_REMATCH[1]}"
  [[ "${lines[3]:-}" =~ ^capabilities:\ \[([a-z,\ ]*)\]$ ]] || fail "$src:4: expected an inline flow list 'capabilities: [a, b]'"
  caps_raw="${BASH_REMATCH[1]}"
  [[ "${lines[4]:-}" == "---" ]] || fail "$src:5: front matter must close with '---' (exactly three keys: name, description, capabilities)"

  [[ "$name" == "$base" ]] || fail "$src: name '$name' does not match filename '$base.md'"

  caps_norm="$(tr -d ' ' <<<"$caps_raw")"
  # An empty list (`capabilities: []`) is not a legal role contract — a role that can touch
  # nothing can't do its job — so reject it here rather than let it silently produce a role
  # with no tools at all.
  [[ -n "$caps_norm" ]] || fail "$src:4: capabilities list must not be empty"
  local -a cap_list=()
  IFS=',' read -r -a cap_list <<<"$caps_norm"
  local c
  for c in "${cap_list[@]+"${cap_list[@]}"}"; do
    case "$c" in
      files | shell | browser | azure | github) ;;
      *) fail "$src:4: capability '$c' is not one of files, shell, browser, azure, github" ;;
    esac
  done

  for ((i = 5; i < ${#lines[@]}; i++)); do
    if [[ -n "${lines[$i]//[[:space:]]/}" ]]; then
      [[ "${lines[$i]}" == "---" ]] && fail "$src:$((i + 1)): stray '---' as the first body line breaks front-matter detection"
      break
    fi
  done

  tools="$(tools_for_capabilities "$caps_norm")"

  echo "---"
  echo "# GENERATED by scripts/generate-agent-views.sh from agents/$base.md — do not edit"
  echo "name: $name"
  echo "description: \"$description\""
  [[ -n "$tools" ]] && echo "tools: $tools"
  echo "model: $AGENT_MODEL"
  echo "---"
  for ((i = 5; i < ${#lines[@]}; i++)); do
    echo "${lines[$i]}"
  done
}

main() {
  [[ -d "$agents_dir" ]] || fail "no agents/ directory at $agents_dir"

  local -a srcs=()
  while IFS= read -r -d '' f; do srcs+=("$f"); done < <(find "$agents_dir" -maxdepth 1 -name '*.md' -print0 | sort -z)
  [[ ${#srcs[@]} -gt 0 ]] || fail "no agents/*.md files found"

  # Always generate into a scratch dir first — never write partial output straight into
  # .claude/agents/, so a validation failure on file N can't truncate an already-good file.
  # Deliberately not `local`: the EXIT trap runs after main() returns, when a local would
  # already be unset under `set -u`.
  target_dir="$(mktemp -d)"
  # Capture $? before cleanup and re-exit with it explicitly — an EXIT trap's own exit
  # (implicit or via a bare `rm -rf`) otherwise resets the script's exit status to the
  # trap's, silently turning a `fail` inside generate_one into a false success.
  trap 'rc=$?; rm -rf "$target_dir"; exit $rc' EXIT

  local src base
  for src in "${srcs[@]}"; do
    base="$(basename "$src" .md)"
    generate_one "$src" >"$target_dir/$base.md"
  done

  mkdir -p "$out_dir"
  if $check_mode; then
    local diff_output
    if diff_output="$(diff -r "$out_dir" "$target_dir")"; then
      echo "generate-agent-views --check: OK — .claude/agents/ matches agents/*.md (${#srcs[@]} role files)."
      exit 0
    else
      echo "generate-agent-views --check: .claude/agents/ is stale. Run scripts/generate-agent-views.sh and commit the result." >&2
      echo "$diff_output" >&2
      exit 1
    fi
  else
    find "$out_dir" -maxdepth 1 -name '*.md' -delete
    cp "$target_dir"/*.md "$out_dir"/
    echo "generate-agent-views: wrote ${#srcs[@]} file(s) to .claude/agents/."
  fi
}

main "$@"
